AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM application for dissertation benchmarks

# Global settings for all functions
Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.12

Resources:
  # Defines the CPU-Bound benchmark function
  CpuBoundFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.cpu_bound_handler # Points to the cpu_bound_handler function in app.py
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /cpu-bound
            Method: post

  # Defines the I/O-Bound benchmark function
  IoBoundFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.io_bound_handler # Points to the io_bound_handler function in app.py
      Policies:
        # Grants the function permission to read/write/delete from the specified S3 bucket
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
      Environment:
        Variables:
          # Passes the bucket name to the function as an environment variable
          S3_BUCKET_NAME: !Ref S3BucketName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /io-bound
            Method: post

# Defines a parameter that will be requested when you deploy the application
Parameters:
  S3BucketName:
    Type: String
    Description: The name of the S3 bucket for the I/O-bound function.


Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'